Feature/cc 10508/сс 10514 add to cart phase2
spryker/demo-date-time-configurator-page pull request #1
Opened 2020-10-05 10:50 UTC by pyvovarov-s

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2020-10-09 05:57 UTC, abitskil commented on composer.json
>          }
Run the `spryker-dev-console dev:composer:update-json-files` console command for this module.

2020-10-09 06:03 UTC, abitskil commented on README.md
>  ```
This list of files missing for this module:
- tooling.yml
- psalm-report.json
- phpstan.neon
- phpstan.json
- CHANGELOG.md
- .travis.yml

2020-10-09 06:19 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +use Spryker\Yves\Kernel\AbstractPlugin;
Add  `spryker/kernel` and `spryker-shop/product-configuration-widget-extension` modules to dependencies.

2020-10-09 06:20 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +            ->setModuleName('ProductConfigurationWidget')
The module name should be `DemoDateTimeConfiguratorPage`.

2020-10-09 06:21 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +            ->setTemplateType('view')
Also, I don't see an `option-list` template at the `view` folder on the Yves, copy it from the source.

2020-10-09 07:16 UTC, abitskil commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/ConfiguratorPage.php
> +        if ($this->request->isMethod('GET') && $this->request->query->has(static::REQUEST_PARAMETER_TOKEN)) {
Use `Symfony\Component\HttpFoundation\Request::METHOD_POST` or `\Symfony\Component\HttpFoundation\Request::METHOD_GET`.

2020-10-09 08:05 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Communication/Plugin/Availability/DemoDateTimeConfiguratorAvailabilityStrategyPlugin.php
> +     * - Calculates availability for product configuration instance.
Remove the `instance` word.

2020-10-09 08:18 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeInterface.php
> +     * - Calculates availability for product configuration instance.
Change to the `Calculates availability for product configuration`.

2020-10-09 08:27 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Validator/ProductConfigurationPriceValidator.php
> +    protected const GLOSSARY_KEY_PRODUCT_CONFIGURATION_PRICE_IS_NOT_VALID
Remove line break.

2020-10-09 08:36 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Validator/ProductConfigurationPriceValidator.php
> +        return ($priceMode === static::PRICE_NET_MODE
Change to a more readable variant like this:
`if($priceMode === static::PRICE_NET_MODE){
   return $itemTransfer->getUnitNetPrice() !== static::DEFAULT_DEMO_PRICE;
}

return $itemTransfer->getUnitGrossPrice() !== static::DEFAULT_DEMO_PRICE;
`.

2020-10-09 09:49 UTC, abitskil commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/ConfiguratorPage.php
> +            // Token check?
No, we don't need any token validation at this moment. The SPA will send the request with the token only on then we need a check.

2020-10-09 09:51 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +        return true;
It should be applicable only when `$productConfigurationInstance->getConfiguratorKey()` equals to the `DemoDateTimeConfiguratorPageConfig::getDateTimeConfiguratorKey()`.

2020-10-09 09:54 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Reader/ProductConcreteAvailabilityReader.php
> +    protected function isTypeDemo(StoreTransfer $storeTransfer): bool
Maybe better `isDemoStore()` ?

2020-10-09 09:59 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Reader/ProductConcreteAvailabilityReader.php
> +        $productConfigurationAvailabilityQuantity = $productAvailabilityCriteriaTransfer->getProductConfigurationInstance()
Extract this flow to the method like `resolveProductConfigurationAvailability()`

2020-10-09 10:01 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Communication/Plugin/SalesProductConfigurationGui/DemoDateTimeProductConfigurationRenderPlugin.php
> +        return (bool)$itemTransfer->getSalesOrderItemConfiguration();
It should be applicable only when `$itemTransfer->getSalesOrderItemConfiguration()->getConfiguratorKey()` equals to the `DemoDateTimeConfiguratorPageConfig::getDateTimeConfiguratorKey()`.

2020-10-12 07:11 UTC, pyvovarov-s commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Reader/ProductConcreteAvailabilityReader.php
> +        if (!$productConfigurationAvailabilityQuantity && !$productConcreteAvailabilityTransfer) {
Not need to fix, because of int check. Will leave it as discussed

2020-10-13 06:51 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/SalesProductConfigurationWidget/SalesProductConfigurationPlainRenderStrategyPlugin.php
> +class SalesProductConfigurationPlainRenderStrategyPlugin extends AbstractPlugin implements SalesProductConfigurationRenderStrategyPluginInterface
Rename to the `DemoDateTimeSalesProductConfigurationRenderStrategyPlugin`.

2020-10-15 08:09 UTC, abitskil commented on composer.json
> +    "phpstan": "vendor/bin/phpstan.phar analyse -c tests/phpstan.neon -l 7 src/",
I think this command will not work, check how it is done in the `synchronization-behavior`, enable phpstan check for travis.

2020-10-15 08:12 UTC, abitskil commented on composer.json
> +    "phpstan/phpstan-shim": "^0.11",
Add the `"phpstan/phpstan": "^0.12.35"` as require dev dependency and enable phpstan check in the travis.yml

2020-10-15 08:13 UTC, abitskil commented on .travis.yml
> +    - composer cs-check
Add the phpstan check `composer phpstan`.

2020-10-15 08:21 UTC, abitskil commented on composer.json
> +    "spryker-sdk/product-configuration-sdk": "dev-feature/cc-10508/\u0441\u0441-10514-add-to-cart-phase2",
Change the version to the `^0.1.0`.

2020-10-15 08:33 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Theme/default/views/options-list/options-list.twig
> +{# //todo would be fully reworked in 2nd phase. Will keep it for now as demo version  #}
Remove the todo comment.

2020-10-15 08:34 UTC, abitskil commented on composer.json
> +    "symfony/http-foundation": "^4.2.0"
Add `"spryker-shop/shop-ui"` to dependencies.

2020-10-15 08:37 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/SalesProductConfigurationWidget/DemoDateTimeSalesProductConfigurationRenderStrategyPlugin.php
> +        return true;
It should be applicable only when `SalesOrderItemConfigurationTransfer::getProductConfiguratorKey()===DemoDateTimeConfiguratorPageConfig::DATE_TIME_CONFIGURATOR_KEY`.

2020-10-15 08:44 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Theme/default/views/product-configurator-page/product-configurator-page.twig
> +{% define data = {
Remove this template it's not needed.

2020-10-15 08:53 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeInterface.php
> +interface DemoDateTimeConfiguratorPageFacadeInterface
We have to cover the facade methods with tests.

2020-10-15 09:30 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Validator/ProductConfigurationPriceValidator.php
> +        $checkoutResponseTransfer->setIsSuccess(true);
Don't overwrite `isSuccess` flag because it's possible that some plugin already switched it to `false` and added some errors.

2020-10-15 09:38 UTC, abitskil commented on src/Spryker/Shared/DemoDateTimeConfiguratorPage/Transfer/demo_date_time_configurator_page.transfer.xml
> +<transfers
Run the following console command for this module:
* `in/spryker-dev-console dev:validate-module-transfers -m Spryker.DemoDateTimeConfiguratorPage`.

2020-10-15 09:39 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +     * {@inheritDoc}
Add specification:`- Applicable to items which have a configuration with corresponds key.`.

2020-10-15 09:41 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/SalesProductConfigurationWidget/DemoDateTimeSalesProductConfigurationRenderStrategyPlugin.php
> +    /**
Add `@api`, `@{@inheritDoc}` tags and specification: `- Applicable to items which have a configuration with corresponds key.`.

2020-10-15 09:42 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/SalesProductConfigurationWidget/DemoDateTimeSalesProductConfigurationRenderStrategyPlugin.php
> +    /**
Fix document block as above and add specification: `- Decodes json configuration data.`

2020-10-15 09:45 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Presentation/_partials/order-item-configuration.twig
> +{% for key, configuration in data %}
We have to ask frontend developer to add toggle functionality here like it is done for Yves already.

2020-10-15 09:50 UTC, abitskil commented on src/Spryker/Yves/DemoDateTimeConfiguratorPage/Plugin/ProductConfigurationWidget/DemoDateTimeProductConfigurationRenderStrategyPlugin.php
> +     *
Add specification: `- Decodes json configuration data.`

2020-10-15 09:58 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Reader/ProductConcreteAvailabilityReader.php
> +    protected function createProductAvailabilityCopyWithoutProductInstance(
Fix a method name `createProductAvailabilityCriteriaCopyWithoutProductConfigurationInstance()`.

2020-10-15 12:32 UTC, dmiseev commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Presentation/_partials/order-item-configuration.twig
> +{% for key, configuration in data %}
Let's keep it for FE review.

2020-10-15 12:34 UTC, dmiseev commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeInterface.php
> +interface DemoDateTimeConfiguratorPageFacadeInterface
@StasPiv will take care.

2020-10-16 06:42 UTC, abitskil commented on src/Spryker/Shared/DemoDateTimeConfiguratorPage/Transfer/demo_date_time_configurator_page.transfer.xml
> +        <property name="data" type="array" singular="data"/>
Missed properties: `templateType`, `templateName`, try to run transfer object definition validator console command one more time.

2020-10-16 06:49 UTC, abitskil commented on composer.json
> +    "phpstan/phpstan-shim": "^0.11",
Remove the `"phpstan/phpstan-shim"` it is no longer needed for the phpstan with a version higher than `0.12.0`.

2020-10-16 06:57 UTC, abitskil commented on composer.json
> +    "phpstan/phpstan": "^0.12.35",
Add `"spryker/testify": "*"`.

2020-10-16 07:03 UTC, abitskil commented on tests/SprykerTest/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeTest.php
> +    public function testFindProductConcreteAvailabilityWillReturnNullWhenAvailabilityNotSet(): void
Fix the name `testFindProductConcreteAvailabilityWillReturnNullWhenAvailabilityIsNotSet`.

2020-10-16 08:26 UTC, abitskil commented on tests/SprykerTest/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeTest.php
> +                ItemTransfer::UNIT_GROSS_PRICE => 1,
It's not a net price.

2020-10-16 08:29 UTC, abitskil commented on tests/SprykerTest/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeTest.php
> +                ItemTransfer::UNIT_GROSS_PRICE => 1,
It should not pass with wrong price.

2020-10-16 08:31 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Validator/ProductConfigurationPriceValidator.php
> +            return $itemTransfer->getUnitNetPrice() !== static::DEFAULT_DEMO_PRICE;
We have an issue here business requirement says that `For AT store the price should be equal to 1000 EUR.`.

2020-10-16 08:36 UTC, abitskil commented on ruleset.xml
> +<?xml version="1.0"?>
Remove this file, seems like it's not needed.

2020-10-16 08:50 UTC, abitskil commented on composer.json
> +    "phpstan/phpstan": "^0.12.35",
Run the console command `vendor/bin/console dev:dependency:fix DemoDateTimeConfiguratorPage`

2020-10-16 08:55 UTC, abitskil commented on tests/SprykerTest/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeTest.php
> +    public function testIsQuoteProductConfigurationPriceValidWillTrueWhenNotDemoStore(): void
Add `WillReturn`.

2020-10-16 11:39 UTC, abitskil commented on src/Spryker/Shared/DemoDateTimeConfiguratorPage/Transfer/demo_date_time_configurator_page.transfer.xml
> +        <property name="templateType" type="string"/>
Remove duplicated field definiton.

2020-10-16 11:49 UTC, abitskil reviewed
From the BE side, it's approved.

2020-10-19 08:32 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/DemoDateTimeConfiguratorPageDependencyProvider.php
> +    public const SERVICE_FILESYSTEM = 'SERVICE_FILESYSTEM';
Rename to the `SYMFONY_FILE_SYSTEM` or `FILE_SYSTEM`  it is not a service.

2020-10-19 08:53 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/DemoDateTimeConfiguratorPageConfig.php
> +     * Path to the configurator frontend request ready directory.
Maybe better would be `Path to the configurator frontend web root directory.`

2020-10-19 08:54 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Communication/Console/ProductConfiguratorBuildFrontendConsole.php
> +class ProductConfiguratorBuildFrontendConsole extends Console
Change the name to `DemoDateTimeProductConfiguratorBuildFrontendConsole`.

2020-10-19 08:57 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageFacadeInterface.php
> +     * - Copies frontend dist directory to the public folder.
Copies frontend dist directory to the configurator public folder.

2020-10-19 08:58 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/Builder/FrontendBuilderInterface.php
> +    public function build(LoggerInterface $logger);
Add return type hint.

2020-10-19 09:01 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/DemoDateTimeConfiguratorPageDependencyProvider.php
> +    protected function addFilesystemService(Container $container): Container
Rename to the  `addFilesystem()`.

2020-10-19 09:02 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Business/DemoDateTimeConfiguratorPageBusinessFactory.php
> +    public function getFilesystemService(): Filesystem
Rename to the `getFileSystem()`.

2020-10-19 09:55 UTC, abitskil approved these changes
From the BE side, it's approved.

2020-10-19 16:23 UTC, gund requested changes
`dist` folder must be removed from git index as this is a compiled artifact.

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/configurator.service.ts
> +        productData.configuration = JSON.stringify(configuration);
It seems very inefficient to constantly re-parse JSON between every update.
Please store plain objects and update them directly and only stringify them before consumption (like view).

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/configurator.service.ts
> +        return JSON.parse(productData.display_data);
Again, services should not care about formatting data for displaying.
Please move this logic to the template.

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/http.service.ts
> +export class HttpService {
This service name is too generic.
Please rename it to reflect what is it meant for (ex. `ProductService`, `ProductPersistanceService`).

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/http.service.ts
> +            params: new HttpParams().set('getConfigurationByToken', this.token)
Params can be constructed from plain objects, please use them:
```suggestion
            params: { getConfigurationByToken: this.token }
```

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/http.service.ts
> +        return this.http.post<ProductData>(`?prepareConfiguration=${this.token}`, data);
Please pass params as a third argument object with `params` key
```suggestion
        return this.http.post<ProductData>('/', data, { params: { prepareConfiguration: this.token } });
```

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/http.service.ts
> +        return locationSearchArr[locationSearchArr.length - 1];
Please read the URL once on init and then store the value and return it.

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/services/types.ts
> +    data?: Array<any>;
Please use `...[]` for array notation
```suggestion
    data?: any[];
```

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/index.html
> +</html>
There is an autogenerated `index.html` file in dist that is supposed to be used for serving.
Can you remove this and use autogenerated one instead?

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/information-list/information-list.component.ts
> +            },
It would be much better if you would expose `httpService.productData` as an observable and then use it here to create an `items` observable by simply mapping it.
Otherwise this component will not render proper data if it is rendered before the product data is loaded.

2020-10-19 16:23 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/app.component.html
> +    </select>
Why do you need to render laguages into the view if they are hidden?
You already have a method to update the language in the component class...

2020-10-20 06:51 UTC, abitskil commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/app.component.ts
> +                    volume_prices: `{"volume_prices":[{"quantity":3,"net_price":350,"gross_price":385},{"quantity":8,"net_price":340,"gross_price":375}]}`
Because it's a demo example of the configurator page.

2020-10-20 06:51 UTC, galitskye commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/footer/footer.component.html
> +    {{ 'global.title' | translate }}
It's by design.

2020-10-20 06:57 UTC, galitskye commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/product-details/product-details.component.html
> +                <input type="hidden" name="productConfigurationInstance[prices][EUR][priceData]" value="{{ productData.volume_prices }}">
This app only demo. All other prices you can see are hardcoded too.

2020-10-20 07:03 UTC, galitskye commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/product-details/product-details.component.ts
> +    totalPrice = 43723;
This is only demo

2020-10-20 07:48 UTC, galitskye commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/app.component.html
> +    </select>
Sorry. I's an extra code. I removed it

2020-10-20 08:37 UTC, abitskil commented on src/Spryker/Zed/DemoDateTimeConfiguratorPage/Presentation/_partials/order-item-configuration.twig
> +{% for key, configuration in data %}
@galitskye don't forget about order item configuration display, do it in another branch.

2020-10-20 13:33 UTC, galitskye commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/index.html
> +</html>
This index.html was provided by BE. We can't use index.html from public `dist` folder

2020-10-21 15:47 UTC, gund approved these changes

2020-10-22 13:27 UTC, gund commented on src/Spryker/Configurator/DemoDateTimeConfiguratorPage/Theme/ConfiguratorApplication/src/app/product-details/product-details.component.ts
> +        this.handleSubmit();
Why is form submitted when input `productData` changes?
This seems non obvious and confusing...

2020-10-23 08:10 UTC, merged